spring:
  application:
    name: hc-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/murphy-cloud/cloud_config/ #配置git仓库的地址
          #search-paths: cloud_config #git仓库地址下的相对地址，可以配置多个，用逗号分隔
          username: 359009471@qq.com
          password: cengjing88
      label: master
server:
  port: 18100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18000/eureka/